// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Clear in-memory caches on any auth state change to prevent
// cross-user data leaks when a user signs out/in in the same tab.
supabase.auth.onAuthStateChange(() => {
  import("@/hooks/useContacts").then((m) => m.invalidateContactsCache?.());
  import("@/hooks/useCompanies").then((m) => m.invalidateCompaniesCache?.());
});